rust: Fix build break because of download-ci-llvm
-----------------------------------------------------------------------
| thread 'main' panicked at src/core/config/config.rs:2047:13:
| setting build-target.llvm-config is incompatible with download-ci-llvm.
-----------------------------------------------------------------------

Disable the automatic download of pre-built LLVM binaries, ensuring
compatibility with local LLVM builds and preventing conflicts with other
configuration settings.

(From OE-Core rev: 8a9b87cf20792a0ed85a7e79a3eeecd14ec7cf1e)

Signed-off-by: Deepesh Varatharajan <Deepesh.Varatharajan@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>