openssh: Increase MaxStartups and MaxSessions
Fixes the following failures:

while runnig oe-selftest for gcc, testcases that need to be run on qemu
are not running due to below failures:
- kex_exchange_identification: read: Connection reset by peer^M
   Connection reset by 192.168.7.2 port 22^M
   ERROR: Couldn't create remote directory /tmp/runtest.3549814 on ssh
To resolve kex exchange identification error increased the MaxStartups.

while running oe-selftest for gcc, with allowing multiple ssh sessions
some testcases are failing due to below failures:
-mux_client_request_session: session request failed: Session open refused by peer
 Host key verification failed.
 ERROR: Couldn't create remote directory /tmp/runtest.3658735 on linux-ssh

To resolve mux_client_request_session request failures increased
MaxSessions.

(From OE-Core rev: 4df50b5dbcd27c9ff01a81e52f30e90157acba9e)

Signed-off-by: Harish Sadineni <Harish.Sadineni@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>